'use client'

import React, { useContext, useEffect } from 'react'
import type { Metadata } from 'next'
import './globals.css'
import AppContextProvider from '@/context/AppContext'
import AsideRight from '@/components/AsideRight'
import AsideLeft from '@/components/AsideLeft'
import { AppContext } from '@/context/AppContext';
import { redirect } from 'next/navigation';


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

interface RootLayoutProps {
  children: React.ReactNode;
  auth: React.ReactNode;
}

export default function RootLayout({ children, auth }: RootLayoutProps) {
  const isLogged = true;

  return (
    <AppContextProvider>
      <html lang="en">
        <body>
          {isLogged
            ?
            (<div id="_next" className='bg-white duration-200'>
              <div id="content" className='md:px-3 mx-auto max-w-screen-xl w-full grid grid-cols-1 md:grid-cols-[_300px_1fr_] lg:grid-cols-[_300px_1fr_300px_] gap-2'>
                <AsideLeft />
                {children}
                <AsideRight />
              </div>
            </div>)
            :
            (<div>{auth}</div>)}
        </body>
      </html>
    </AppContextProvider>
  )
}
